
DATA: LV_IDMSG      TYPE SY-MSGID, "ID of the Messages Program "
      LV_NUMMSG     TYPE SY-MSGNO, "Message's Number"
      LV_TYMSG      TYPE SY-MSGTY, "Message's Type"
      LV_TYMSG2     TYPE SY-MSGV1, "Message's Text"
      LV_TRANSCODE  TYPE SY-TOCDE, "Transaction's Code"
      LV_RETURN     TYPE SY-SUBRC, "Function's Return Code"
      LV_DATE       TYPE SY-DATUM, "System Date"
      LV_HOUR       TYPE SY-UZEIT, "System Hour"
      LV_NAME       TYPE SY-UNAME, "System User Name"
      LV_IDPRO      TYPE SY-REPID, "ID Program"
      LV_TRANS      TYPE SY-CALLD, "Transaction Name"
      LV_TRANSP     TYPE SY-CALLP, "Transaction Program Name"
      LV_DYNNPRO    TYPE SY-DYNRUCOD, "Program Name DynnPro"
      LV_UCOMM      TYPE SY-UCOMM, "Command Function to Dynpro"
      LV_LIST       TYPE SY-LISEL, "Index List"
      LV_CODET      TYPE SY_TCODE, "Transaction Code"
      LV_INDEX      TYPE SY_TABIX, "Current Index of a Internal Table"
      LV_LINESCREEN TYPE SY-CUROW, "Current line of screen of a Dynpro"
      LV_COLSCREEN  TYPE SY-CUCOL, "Current column of screen of a Dynpro"
      LV_GROUPDYN   TYPE SY-DYNGR, "Name of Dynpro Group"
      LV_GROUPDYNUM TYPE SY-DYNNR, "Number of dialogs from a Dynpro Group"
      LV_TYPFUNC    TYPE SY-PFKEY, "Function of a typ function"
      LV_TYPFUNCS   TYPE SY-PFKEYS, "List of function keys used in a dialog screen."
      LV_DYNNUM     TYPE SY-DYNNR, "Number of Dynpro Screen"
      LV_DYNNTYTLE  TYPE SY-TITLE, "Number of Dynpro Title"
      LV_BINPUT     TYPE SY-BINPT, "Index of Binary Entry"

"-------------------------------------
